# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Header Menu
menu:
  Home: /
  About: about
  Contact: contact
rss: /atom.xml


since: 2020

# Set default keywords (Use a comma to separate)
keywords: ""

# Put your favicon.ico or avatar.jpg into `hexo-site/themes/hiker/source/` directory.
avatar: 
  enable: true
  border: true
  width: 124
  height: 124
  top: 0
  url: css/images/logo.png


# Homepage
# eg. home_background_image: [css/images/home-bg.jpg, http://t.cn/RMbvEza]
# eg. mode: image | polyline | trianglify
home_background_image:
  enable: true
  mode: video
  url: css/videos/vid1.mp4

home_logo: 
  url: css/images/logo.png

# AboutPage background
about_bg_image: 
  enable: true
  url: css/videos/vid2.mp4

# Archive pagination
archive_pagination: true


# Post Article's Content
post_catalog:
  enable: true
# 开启主页摘要
post_excerpt: true


# Content
fancybox: true

# Search
search:
    insight: true # you need to install `hexo-generator-json-content` before using Insight Search
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false



# Code Highlight theme
# Available value:
#    default | gray | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: default


# Article theme color
# Available value:
#    random | orange | blue | red | green | black
theme_color: random


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive


# widget behavior
archive_type: 'monthly'
show_count: true

# post edit url, modify your post online for convenience
# If you put your blog on GitHub, it should look like:
# https://github.com/username/blog/edit/master/source/_posts/
post_edit_url: 
